name: 'Version and Changelog Generator'
description: 'Generates version and changelog using bump-n-go'
inputs:
  release-type:
    description: 'The type of release to create (major, minor, patch). If not specified, bump-n-go will determine automatically.'
    required: false
  dry-run:
    description: 'Run in dry-run mode without making changes'
    required: false
    default: 'false'
outputs:
runs:
  using: "composite"
  steps:
    - name: "Setup Node.js"
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: "24"
        cache: "npm"
    - name: Setup dependencies
      uses: .github/actions/cached-node-modules@29979bc5339bf54f76a11ac36ff67701986bb0f0
      with:
        nodeVersion: "24"
    - name: Run bump-n-go
      id: bump-version
      shell: bash
      run: |
        # Build CLI arguments
        CMD_ARGS=""
        
        # Add release-type only if specified
        if [[ -n "${{ inputs.release-type }}" ]]; then
          CMD_ARGS="${{ inputs.release-type }}"
        fi
        
        # Add dry-run flag if enabled
        if [[ "${{ inputs.dry-run }}" == "true" ]]; then
          if [[ -n "$CMD_ARGS" ]]; then
            CMD_ARGS="$CMD_ARGS --dry-run"
          else
            CMD_ARGS="--dry-run"
          fi
        fi
        
        # Run bump-n-go with the constructed arguments
        npx bump-n-go $CMD_ARGS
